server.port=8080

spring.mongodb.uri=mongodb+srv://ksaijoshna0857_db_user:Joshna0857@cluster0.dthksyk.mongodb.net/agricrop_db?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://ksaijoshna0857_db_user:Joshna0857@cluster0.dthksyk.mongodb.net/agricrop_db?retryWrites=true&w=majority